version: "3.4"

services:
  redis:
    container_name: redis
    image: ghcr.io/redisgrafana/redis-opencv:latest
    volumes:
      - ./ai:/home/ai/
    ports:
      - 6379:6379

  grafana:
    container_name: grafana
    image: ghcr.io/redisgrafana/redis-app:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_ENABLE_GZIP=true
      - GF_USERS_DEFAULT_THEME=light
      - GF_INSTALL_PLUGINS=volkovlabs-image-panel
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - ./dashboards:/var/lib/grafana/dashboards


  crowd-human-head-body:
    image: mehran69/crowd-human-head-body
    container_name: crowd-human-head-body
    working_dir: /home/head_body_detection_yolov3/
    entrypoint: /home/head_body_detection_yolov3/init.sh
    ports:
      - 8000:8000
    volumes:
      - ../head_body_detection_yolov3/:/home/head_body_detection_yolov3/
    tty: true